

services:
  postgres:
    image: postgres
    container_name: dsa-platform
    restart: unless-stopped
    environment:
      POSTGRES_USER: manng
      POSTGRES_PASSWORD: manng
      POSTGRES_DB: manng
    ports:
      - "5432:5432"
    volumes:  
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manng"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

